version: "2.1"
services:
  resilio-sync:
    image: "linuxserver/resilio-sync"
    container_name: "resilio-sync"
    environment:
      - "PUID=${ENVIRONMENT_PUID}"
      - "PGID=${ENVIRONMENT_PGID}"
      - "UMASK=022"
    volumes:
      - "${VOLUME_ROOT}/resilio-sync/config:/config"
      - "${VOLUME_ROOT}/resilio-sync/downloads:/downloads"
      - "/:/sync"
    ports:
      - "${PORT_WEBUI}:8888"
      - "55555:55555"
    restart: "unless-stopped"
    labels:
      - "com.centurylinklabs.watchtower.enable=${LABEL_WATCHTOWER_ENABLE}"
