version: "3.3"
networks:
  default:
    name: ${NETWORK_NAME}
    external: ${NETWORK_IS_EXTERNAL}
services:
  bitwardenrs1:
    image: "bitwardenrs/server"
    container_name: "${CONTAINER_NAME1}"
    ports:
      - "${PORT_HTTP1}:80"
    volumes:
      - "${VOLUME_ROOT}/bitwardenrs/${CONTAINER_NAME1}/bw-data:/data"
    restart: "unless-stopped"
    labels:
      - "com.centurylinklabs.watchtower.enable=${LABEL_WATCHTOWER_ENABLE}"
  bitwardenrs2:
    image: "bitwardenrs/server"
    container_name: "${CONTAINER_NAME2}"
    ports:
      - "${PORT_HTTP2}:80"
    volumes:
      - "${VOLUME_ROOT}/bitwardenrs/${CONTAINER_NAME2}/bw-data:/data"
    restart: "unless-stopped"
    labels:
      - "com.centurylinklabs.watchtower.enable=${LABEL_WATCHTOWER_ENABLE}"
