version: "3.7"
networks:
  default:
    external: "${NETWORK_IS_EXTERNAL}"
    name: "${NETWORK_NAME}"
services:
  plex:
    image: "linuxserver/plex"
    container_name: "plex"
    environment:
      - "PUID=${ENVIRONMENT_PUID}"
      - "PGID=${ENVIRONMENT_PGID}"
      - "UMASK=022"
      - "TZ=America/Los_Angeles"
      - "VERSION=docker"
      - "PLEX_CLAIM=${PLEX_CLAIM}"
    volumes:
      - "${VOLUME_ROOT}/plex/config:/config"
      - "${VOLUME_ROOT}/plex/tv:/tv"
      - "${MEDIA_ROOT}:/data"
    devices:
      - "/dev/dri:/dev/dri"
    networks:
      default:
        ipv4_address: "${NETWORK_IPV4_ADDRESS}"
    restart: "unless-stopped"
