version: "3.7"

services:
  plex:
    image: "plexinc/pms-docker:latest"
    container_name: "plex"
    environment:
      - TZ=America/Los_Angeles
      - PLEX_CLAIM=${PLEX_CLAIM}
      - PLEX_UID=${PLEX_UID}
      - PLEX_GID=${PLEX_GID}
    volumes:
      - "${VOLUME_ROOT}/plex/config:/config"
      - "${VOLUME_ROOT}/nas_multimedia_kids:/media/kids"
      - "${VOLUME_ROOT}/nas_multimedia_parents:/media/parents"
    ports:
      - "32400:32400"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    runtime: nvidia
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
