version: "2"
networks:
  default:   # externally created network (later in article)
    external: "${NETWORK_IS_EXTERNAL}"
    name: "${NETWORK_NAME}"
services:
  pihole:
    container_name: ${CONTAINER_NAME}
    image: pihole/pihole # check the latest version on docker hub.
    cap_add:
      - "NET_ADMIN"
    networks:
      default:
        ipv4_address: "${NETWORK_IPV4_ADDRESS}" # the IP of the pihole container
    dns:
      - "127.0.0.1" # use local DNS, since the pihole
      - "1.1.1.1" # optional fallback DNS
    ports: # expose all pihole ports.
      - "443:443/tcp"
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
    volumes:
      - "${VOLUME_ROOT}/pihole/etc-pihole:/etc/pihole"
      - "${VOLUME_ROOT}/pihole/etc-dnsmasq.d:/etc/dnsmasq.d"
    environment: # set variables for pihole configuration.
      ServerIP: "${NETWORK_IPV4_ADDRESS}" # must match ipv4_address above
      WEBPASSWORD: "${ENVIRONMENT_WEBPASSWORD}"
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=${LABEL_WATCHTOWER_ENABLE}"
