version: "3"

services:
  watchtower:
    image: "${IMAGE}"
    container_name: "watchtower"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/etc/timezone:/etc/timezone:ro"
    ports:
      - "${PORT_ADMIN}:8080"
    environment:
      - "WATCHTOWER_CLEANUP=true"
      - "WATCHTOWER_LABEL_ENABLE=true"
      - "WATCHTOWER_INCLUDE_RESTARTING=true"
    command: "${COMMAND}"
    labels:
      - "com.centurylinklabs.watchtower.enable=${LABEL_WATCHTOWER_ENABLE}"
