version: "3"

services:
  cadvisor:
    image: "gcr.io/cadvisor/cadvisor:${IMAGE_VERSION}"
    container_name: "cadvisor"
    restart: "unless-stopped"
    ports:
      - "${PORT_ADMIN}:8080"
    privileged: true
    volumes:
      - "/:/rootfs:ro"
      - "/var/run:/var/run:ro"
      - "/sys:/sys:ro"
      - "/var/lib/docker/:/var/lib/docker:ro"
      - "/dev/disk/:/dev/disk:ro"
      - "/etc/machine-id:/etc/machine-id:ro"
      - "/var/lib/dbus/machine-id:/var/lib/dbus/machine-id:ro"
    devices:
      - /dev/kmsg:/dev/kmsg
    labels:
      - "com.centurylinklabs.watchtower.enable=${LABEL_WATCHTOWER_ENABLE}"
