version: "3.3"
services:
  portainer:
    container_name: "portainer"
    image: "portainer/portainer-ce"
    restart: "unless-stopped"
    ports:
      - "${PORT_ADMIN}:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "${VOLUME_ROOT}/portainer:/data"
    labels:
      - "com.centurylinklabs.watchtower.enable=${LABEL_WATCHTOWER_ENABLE}"
